<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><title>Zend Server 6 Beta is now available!</title>

<style>
body,td, p {font-size:12px;color:#394852;line-height:150%;font-family: Arial, sans-serif;}
ul { padding: 0; margin: 5px auto; list-style-image: url(http://static.zend.com/topics/green-bullet.gif); }
ul li{ margin-left:15px; padding: 0 0 3px 0; list-style-image: url(http://static.zend.com/topics/green-bullet.gif); }
a:link { color:#397fad; text-decoration: underline; }
a:visited {color:#397fad;text-decoration: underline;}
a:hover {color:#7bc1ea; text-decoration: none;}
#sideCol {background-color:#edeff0;text-align:left;}
.sideColText {font-family::Arial, sans-serif; font-size:11px; color:#394852;}
</style>
</head>
<body>
<table border="0" cellpadding="0" cellspacing="0" width="69%">
<tbody>
<tr>
<td align="left" valign="top">
<table border="0" cellpadding="0" cellspacing="0" width=687">
<tbody>
<tr>
<td width="701" style="border: 1px solid rgb(158, 169, 174);">
<!-- HEADER -->
<table bgcolor="#b6c2c8" border="0" cellpadding="10" cellspacing="0" width="687">
<tbody>
<tr>
<td style="background-color: rgb(182, 194, 200); text-align: left;" align="left" bgcolor="#b6c2c8" width="549"><a href="http://www.zend.com/" target="_top"><img alt="Zend - The PHP Company" src="http://static.zend.com/topics/zend-logo-graybg-email.gif" style="border: 0px solid ; width: 142px; height: 41px;" border="0" height="41" width="142"></a></td>
</tr>
</tbody>
</table>
<!-- BODY -->
<?php echo $content; ?>
</tr>
<tr>
  <td colspan="2" align="left" valign="top" bgcolor="#ffffff" style="font-size: 9px; color: rgb(57, 72, 82); line-height: 100%; font-family: Arial,sans-serif; padding: 10px;">&copy; 2013 Zend Corporation. Zend Server is a registered trademark of Zend Technologies Ltd. All other trademarks are the property of their respective owners.</td>
  </tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</body></html>