<table align="left" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="687">
<tbody>
<tr>
  <td colspan="2" align="left" valign="top" bgcolor="#ffffff"><img src="http://static.zend.com/topics/ZS6-users-assistance-Welcome-top-banner-687x50px-02.png" alt="Welcome to Zend Server 6 Mail Services" width="687" height="50" border="0"></td>
  </tr>
<tr>
  <td align="left" valign="top" bgcolor="#ffffff" style="width: 100%; font-size: 12px; color: rgb(57, 72, 82); line-height: 150%; font-family: Arial,sans-serif; padding-left: 10px; padding-top: 10px;">
    <p><strong style="font-size: 20px; color: rgb(0, 143, 213); line-height: 100%; font-family: Trebuchet MS; letter-spacing:0px;">Congratulations!</strong></p>
    <p>You have successfully configured your mail account for receiving information from Zend Server.<br>
      You are just one step away from receiving system notifications, monitoring events and audits from Zend Server:</p>
    <table style="width: 100%;">
    <tr>
    <td style="vertical-align: top; padding-top: 18px;">
    <TABLE border=0 cellSpacing=0 cellPadding=0 >
      <TBODY>
        <TR>
          <TD width="400" style="LINE-HEIGHT: 150%; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #394852; FONT-SIZE: 12px; padding-left: 10px;">
          <TABLE width="380" border=0 cellPadding=0 cellSpacing=0>
            <TBODY>
              <TR style="height: 35px;">
                <TD width="4" valign="top"><SPAN style="color: rgb(0, 143, 213); FONT-SIZE: 12px"><img src="http://static.zend.com/topics/help-icon-16x16px.png" style="margin-top: 6px;" /></SPAN></TD>
                <TD width=6>&nbsp;</TD>
                <TD width="299" style="LINE-HEIGHT: 150%; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #394852; FONT-SIZE: 12px; padding-bottom:5px"><a href="<?php echo $this->helpLink('editing_rules'); ?>">How do I configure my monitoring rules to send me event info? </a></TD>
                </TR>
              <TR style="height: 35px;">
                <TD vAlign=top><SPAN style="color: rgb(0, 143, 213); FONT-SIZE: 12px"><img src="http://static.zend.com/topics/help-icon-16x16px.png" style="margin-top: 6px;" /></SPAN></TD>
                <TD width=6>&nbsp;</TD>
                <TD style="LINE-HEIGHT: 150%; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #394852; FONT-SIZE: 12px; padding-bottom:5px"><a href="<?php echo $this->helpLink('working_with_auditing'); ?>">How do I  configure Zend Server to send me audited actions?</a></TD>
                </TR>
                <TR style="height: 35px;">
                <TD vAlign=top><SPAN style="color: rgb(0, 143, 213); FONT-SIZE: 12px"><img src="http://static.zend.com/topics/help-icon-16x16px.png" style="margin-top: 6px;" /></SPAN></TD>
                <TD width=6>&nbsp;</TD>
                <TD style="LINE-HEIGHT: 150%; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #394852; FONT-SIZE: 12px; padding-bottom:5px"><a href="<?php echo $this->helpLink('working_with_the_notification_center'); ?>">How do I configure the Notification Center to send me system notifications?</a></TD>
                </TR>
              </TBODY>
            </TABLE></TD>
          </TR>
        </TBODY>
</TABLE>
</td>
    <td><img src="http://static.zend.com/topics/Paper-Airplane-image-261x279px.png" border="0"></td>
    </tr>
    </table>
</td>